
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        STUDENT_ADD_NEW : "STUDENT_ADD_NEW",
        STUDENT_EDIT:"STUDENT_EDIT",
        TEACHER_ADD_NEW : "TEACHER_ADD_NEW",
        TAIKHOAN_ADD:"TAIKHOAN_ADD",
        TAIKHOAN_EDIT:"TAIKHOAN_EDIT",
        TEACHER_EDIT:"TEACHER_EDIT",
        BOMON_ADD_NEW:"BOMON_ADD_NEW",
        BOMON_EDIT:"BOMON_EDIT",
        CHUYENMON_ADD_NEW:"CHUYENMON_ADD_NEW",
        CHUYENMON_EDIT:"CHUYENMON_EDIT",
        IMPORT_SINHVIEN:"IMPORT_SINHVIEN",
        DANGKY_EDIT:"DANGKY_EDIT",
        GHICHU_ADD:"GHICHU_ADD",
        GHICHUDC_ADD:"GHICHUDC_ADD",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
